import os
from dotenv import load_dotenv

load_dotenv()

BAROBILL_FTP_HOST = os.getenv("BAROBILL_FTP_HOST")
BAROBILL_FTP_PORT = os.getenv("BAROBILL_FTP_PORT")
BAROBILL_FTP_USER = os.getenv("BAROBILL_FTP_USER")
BAROBILL_FTP_PASSWORD = os.getenv("BAROBILL_FTP_PASSWORD")
BAROBILL_CERTKEY = os.getenv("BAROBILL_CERTKEY")
BAROBILL_CORPNUM = os.getenv("BAROBILL_CORPNUM")
BAROBILL_TO_NUMBER = os.getenv("BAROBILL_TO_NUMBER")
BAROBILL_ID = os.getenv("BAROBILL_ID")
TEST_FROM_NUMBER = os.getenv("TEST_FROM_NUMBER")
TEST_TO_NUMBER = os.getenv("TEST_TO_NUMBER")