name: Deploy to AWS EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Copy files to EC2 instance with pem file with aws cli
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        source: "./server"
        target: "/home/ubuntu/server"

    - name: EC2 Docker Run
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker rm -f $(docker ps -qa)
          docker rmi -f $(docker images -qa)
          docker build server -t server --no-cache
          docker run -d -p 80:80 --name server server

