name: Deploy to AWS EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Copy files to EC2 instance with pem file with aws cli
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        source: "./server"
        target: "/home/ubuntu/server_${{ github.head_ref }}"
        overwrite: true

    - name: EC2 Docker Run
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker rm -f $(docker ps -qa)
          docker rmi -f $(docker images -qa)
          image_name=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 32 | head -n 1)
          docker build --no-cache server_${{ github.head_ref }} -t $image_name
          docker run -d -p 80:80 --name server_${{ github.head_ref }} $image_name

